name: Build Android APK

on:
  workflow_dispatch: # This allows you to click a button on GitHub to trigger the build manually

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'mobile/package-lock.json'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: Install Project Dependencies
        working-directory: ./mobile
        run: npm ci --legacy-peer-deps

      - name: Build APK using EAS Local
        working-directory: ./mobile
        # By running EAS with --local in GitHub, we use GitHub's fast servers to compile it instantly
        # instead of waiting in the Expo cloud queue.
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --profile preview --local --non-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SobaHealth-App-APK
          # EAS places local builds in the root directory
          path: ./mobile/*.apk